### ISSUE TITLE
JavaScript のインデントが統一されていない

### ISSUE THREAD

**Issue by tom-konda** [K-Sakanoshita/mapmaker#16]
ライブラリを除いた、JavaScript ファイルのインデントがファイルによってスペースだったりタブだったり統一されていないようです。

- スペース
  - `/lib/basiclib.js`
  - `/lib/geolib.js`
- タブ
  - 上記以外のすべての JavaScript ファイル

今後のインデントの不統一を防ぐため、Prettier のようなコードフォーマッタを導入する予定はありますか？

**Comment by K-Sakanoshita** [comment]
ご確認ありがとうございます。
VSCodeの操作感が同じなので、インデントの不統一に気がついてなかったです。
ツールの導入はこれから考えますが、今後は「タブ」で統一したいと思います。

**Comment by tom-konda** [comment]
> ツールの導入はこれから考えますが、今後は「タブ」で統一したいと思います。

了解です。
最初に調査漏れだったのですが、CSS 側も `/css/basemenu.css` はスペースでインデントしてました。
こちらも確認お願いします。

> VSCodeの操作感が同じなので、インデントの不統一に気がついてなかったです。

確かに、VSCode はインデントの設定でほぼ見た目を同じにできますね😲
