### ISSUE TITLE
防災訓練DIGで使用するする刻のお願い

### ISSUE THREAD

**Issue by hirof1** [K-Sakanoshita/mapmaker#3]
地図を使用した防災訓練でDIGがあります。
市を全域カバーしてその地図をたたみB0版の2倍ぐらいに印刷して利用します。
加古川市全域をカバーした範囲で、作成すると建物の表示がされなくなります。
改修は難しいでしょうか？

ズームレベルの加減で、加古川本流の青色で塗りつぶされないことがあります。
これは何かのバグでしょうか？

**Comment by hirof1** [comment]
地図を使用した防災訓練でDIGがあります。
市を全域カバーしてその地図をたたみB0版の2倍ぐらいに印刷して利用します。
加古川市全域をカバーした範囲で、作成すると建物の表示がされなくなります。
改修は難しいでしょうか？

ズームレベルの加減で、加古川本流の青色で塗りつぶされないことがあります。
これは何かのバグでしょうか？

**Comment by K-Sakanoshita** [comment]
あまりに広い範囲だとサーバーの負担が高くタイムアウトしてしまうため制限させています。
現状、ズームレベル15から建物を表示させていますが、どの程度のズームレベルを希望するか教えてください。

なお、市全域の広域地図であれば、OSM標準地図を使った方が良いかも知れません。
BigmapというWebサイトを使うことで、少し手間とスキルは掛かりますが広域地図画像が取得出来ます。
※使い方がわからなければ、私の方で作成しても良いのでご連絡ください。

**Comment by K-Sakanoshita** [comment]
アップデートによりズームレベル11でも広域地図は出せるようになりました。
ただ、建物はズームレベル15より小さい段階で出力すると崩れてしまいます（小さすぎて）
